version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: '@types/jest'
        versions: ['>=30.0.0']
      - dependency-name: 'jest'
        versions: ['>=30.0.0']
      - dependency-name: 'jest-config'
        versions: ['>=30.0.0']
